# Generated by Django 3.1.5 on 2021-01-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('author', models.TextField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('tags', models.TextField()),
                ('designation', models.CharField(max_length=100)),
                ('disclosures', models.TextField()),
                ('status', models.CharField(choices=[('Working Paper', 'Working Paper'), ('Final', 'Final')], max_length=50)),
                ('peer_reviewed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Under Review', 'Under Review')], max_length=50)),
                ('affiliation', models.CharField(choices=[('Volunteer', 'Volunteer'), ('Fellow', 'Fellow'), ('Unaffiliated', 'Unaffiliated')], max_length=50)),
                ('external_funding', models.BooleanField(default=False)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.journal')),
            ],
        ),
    ]
